<?php

/**
 * PlugintdSubpageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdSubpageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdSubpageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdSubpage');
    }
}