<?php

/**
 * PlugintdSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugintdSubpage extends BasetdSubpage
{
  /**
   * Returns id value.
   *
   * @return Integer - id value.
   */
  public function getIdValue()
  {
    return $this->getId();
  }

  /**
   * Returns shortened content of the static page.
   *
   * @return String - shortened content.
   */
  public function getContentShort()
  {
    return strip_tags(tdTools::getMbShortenedString($this->getContent(), sfConfig::get('td_short_text_sign_count')));
  }

  /**
   * Returns subpage title used as HTML/title.
   *
   * @return String - subpage title.
   */
  public function getTitle()
  {
    return tdTools::getProjectName().' - '.$this->getName();
  }

  /**
   * Activates subpage (and saves itself afterwards).
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
  }

  /**
   * Deactivates subpage (and saves itself afterwards).
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
  }
}
