<?php

/**
 * PlugintdSubpageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdSubpageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PlugintdSubpageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PlugintdSubpage');
  }

  /**
   * Returns a query retrieving a subpage given by the id.
   *
   * @param Integer $id - subpage id.
   * @return Doctrine_Query - query retrieving a subpage.
   */
  public static function getActiveSubpageByIdQuery($id)
  {
    return Doctrine_Query::create()
      ->from('tdSubpage s')
      ->where('s.active = 1')
      ->andWhere('s.id = ?', $id);
  }

  /**
   * Returns a query retrieving a subpage given by the slug.
   *
   * @param String $slug - subpage slug.
   * @return Doctrine_Query - query retrieving a subpage.
   */
  public static function getActiveSubpageBySlugQuery($slug)
  {
    return Doctrine_Query::create()
      ->from('tdSubpage s')
      ->where('s.active = 1')
      ->andWhere('s.slug = ?', $slug);
  }

  /**
   * Returns query retrieving subpage given by id.
   *
   * @param Integer $id - subpage id.
   * @return Doctrine_Query - query retrieving subpage given by id.
   */
  public static function getSubpageByIdQuery($id)
  {
    return Doctrine_Query::create()
      ->from('tdSubpage s')
      ->where('s.id = ?', $id);
  }

  /**
   * Returns query retrieving subpage given by slug.
   *
   * @param String $slug - subpage slug.
   * @return Doctrine_Query - query retrieving subpage given by slug.
   */
  public static function getSubpageBySlugQuery($slug)
  {
    return Doctrine_Query::create()
      ->from('tdSubpage s')
      ->where('s.slug = ?', $slug);
  }
}
