<?php

/**
 * PlugintdConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdConfig');
    }
}