<?php

/**
 * PlugintdConfigTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdConfigTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PlugintdConfigTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PlugintdConfig');
  }

  /**
   * Returns a configuration value given by configuration option name.
   *
   * @param String $value - configuration option name.
   * @return String - configuration option value.
   */
  static public function getConfigValue($value)
  {
    $config = self::getInstance()->findBy('name', $value)->getFirst();
    return $config['value'];
  }
}
