generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tdLink
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tdLink
    with_doctrine_route:   true
    actions_base_class:    sfActions
#    css:                   td_admin

    config:
      actions: ~
      fields:  ~
      list:
#        actions: []
        batch_actions:
          _delete: ~
          activate: ~
          deactivate: ~
        object_actions:
          _edit: ~
          _delete: ~
          activate: ~
          deactivate: ~

      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
