tdSubpage:
  class: sfDoctrineRouteCollection
  options:
    model:                tdSubpage
    module:               tdSubpage
    prefix_path:          /tdSubpage
    column:               id
    with_wildcard_routes: true

td_ajax_subpage_activate:
  url:   /td_ajax_subpage_activate/:id
  param: { module: tdSubpage, action: activate }
  requirements:
    id: \d+

td_ajax_subpage_deactivate:
  url:   /td_ajax_subpage_deactivate/:id
  param: { module: tdSubpage, action: deactivate }
  requirements:
    id: \d+

tdConfig:
  class: sfDoctrineRouteCollection
  options:
    model:                tdConfig
    module:               tdConfig
    prefix_path:          /tdConfig
    column:               id
    with_wildcard_routes: true
